

# CATEGORIES = [
# { 'id': 1, 'color': [0, 0, 128] ,'name': 'aeroplane', 'supercategory': 'vehicle', },
# { 'id': 2, 'color': [0, 128, 0] ,'name': 'bicycle', 'supercategory': 'vehicle', },
# { 'id': 3, 'color': [0, 128, 128] ,'name': 'bird', 'supercategory': 'animal', },
# { 'id': 4, 'color': [128, 0, 0] ,'name': 'boat', 'supercategory': 'vehicle', },
# { 'id': 5, 'color': [128, 0, 128] ,'name': 'bottle', 'supercategory': 'kitchen', },
# { 'id': 6, 'color': [128, 128, 0] ,'name': 'bus', 'supercategory': 'vehicle', },
# { 'id': 7, 'color': [128, 128, 128] ,'name': 'car', 'supercategory': 'vehicle', },
# { 'id': 8, 'color': [0, 0, 64] ,'name': 'cat','supercategory': 'animal',  },
# { 'id': 9, 'color': [0, 0, 192] ,'name': 'chair', 'supercategory': 'furniture', },
# { 'id': 10, 'color': [0, 128, 64] ,'name': 'cow','supercategory': 'animal',  },
# { 'id': 11, 'color': [0, 128, 192] ,'name': 'dining table', 'supercategory': 'furniture', },
# { 'id': 12, 'color': [128, 0, 64] ,'name': 'dog','supercategory': 'animal',  },
# { 'id': 13, 'color': [128, 0, 192] ,'name': 'horse', 'supercategory': 'animal', },
# { 'id': 14, 'color': [128, 128, 64] ,'name': 'motorbike', 'supercategory': 'vehicle', },
# { 'id': 15, 'color': [128, 128, 192] ,'name': 'person', 'supercategory': 'person', },
# { 'id': 16, 'color': [0, 64, 0] ,'name': 'potted plant', 'supercategory': 'furniture', },
# { 'id': 17, 'color': [0, 64, 128] ,'name': 'sheep', 'supercategory': 'animal', },
# { 'id': 18, 'color': [0, 192, 0] ,'name': 'sofa', 'supercategory': 'furniture', },
# { 'id': 19, 'color': [0, 192, 128] ,'name': 'train', 'supercategory': 'vehicle', },
# { 'id': 20, 'color': [128, 64, 0] ,'name': 'tvmonitor', 'supercategory': 'furniture', },
#
# ]

CATEGORIES = [
{ 'id': 1,'name': 'bottle', 'supercategory': 'vehicle', },
{ 'id': 2 ,'name': 'cup', 'supercategory': 'vehicle', },
{ 'id': 3,'name': 'knife', 'supercategory': 'animal', },
{ 'id': 4,'name': 'bowl', 'supercategory': 'vehicle', },
{ 'id': 5,'name': 'wine glass', 'supercategory': 'kitchen', },
{ 'id': 6,'name': 'fork', 'supercategory': 'vehicle', },
{ 'id': 7,'name': 'spoon', 'supercategory': 'vehicle', },
{ 'id': 8,'name': 'banana','supercategory': 'animal',  },
{ 'id': 9,'name': 'apple', 'supercategory': 'furniture', },
{ 'id': 10,'name': 'orange','supercategory': 'animal',  },
{ 'id': 11,'name': 'cake', 'supercategory': 'furniture', },
{ 'id': 12,'name': 'potted plant','supercategory': 'animal',  },
{ 'id': 13,'name': 'mouse', 'supercategory': 'animal', },
{ 'id': 14,'name': 'keyboard', 'supercategory': 'vehicle', },
{ 'id': 15,'name': 'laptop', 'supercategory': 'person', },
{ 'id': 16,'name': 'cell phone', 'supercategory': 'furniture', },
{ 'id': 17,'name': 'book', 'supercategory': 'animal', },
{ 'id': 18,'name': 'clock', 'supercategory': 'furniture', },
{ 'id': 19,'name': 'chair', 'supercategory': 'vehicle', },
{ 'id': 20,'name': 'dining table', 'supercategory': 'furniture', },
{ 'id': 21,'name': 'couch', 'supercategory': 'furniture', },
{ 'id': 22,'name': 'bed', 'supercategory': 'furniture', },
{ 'id': 23,'name': 'toilet', 'supercategory': 'furniture', },
{ 'id': 24,'name': 'television', 'supercategory': 'furniture', },
{ 'id': 25,'name': 'microwave', 'supercategory': 'furniture', },
{ 'id': 26,'name': 'toaster', 'supercategory': 'furniture', },
{ 'id': 27,'name': 'refrigerator', 'supercategory': 'furniture', },
{ 'id': 28,'name': 'oven', 'supercategory': 'furniture', },
{ 'id': 29,'name': 'sink', 'supercategory': 'furniture', },
{ 'id': 30,'name': 'person', 'supercategory': 'furniture', },

]

CLASSES = [
    'BG',
    'bottle',
    'cup',
    'knife',
    'bowl',
    'wine glass',
    'fork',
    'spoon',
    'banana',
    'apple',
    'orange',
    'cake',
    'potted plant',
    'mouse',
    'keyboard',
    'laptop',
    'cell phone',
    'book',
    'clock',
    'chair',
    'dining table',
    'couch',
    'bed',
    'toilet',
    'television',
    'microwave',
    'toaster',
    'refrigerator',
    'oven',
    'sink',
    'person'
]